apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./tekton/00_pvc-tekton-pvc.yaml
  - ./tekton/01_eventlistener.yaml
  - ./tekton/02_trigger-template.yaml
  - ./tekton/03_triggerbinding-app-demo.yaml
  - ./tekton/04_task-fetch-source.yaml
  - ./tekton/05_task-pytest.yaml
  - ./tekton/06_task-s2i.yaml
  - ./tekton/07_task-sign-image.yaml
  - ./tekton/08_task-image-check.yaml
  - ./tekton/09_task-image-scan.yaml
  - ./tekton/10_task-openshift-client.yaml
  - ./tekton/11_task-integration-test.yaml
  - ./tekton/12_task-gitea-set-status.yaml
  - ./tekton/13_task-kaniko.yaml
  - ./tekton/99_pipeline-clone-build-push.yaml
