---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-pvc
  namespace: ${{ values.component_id }}-tekton
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: gp3-csi
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem

