apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cicd-devsec-ops
  namespace: cicd-devsec-ops
spec:
  params:
  - name: pr-number
    value: $(body.pull_request.number)
  - name: GIT_REVISION
    value: $(body.pull_request.head.sha)
  - name: GIT_REPO
    value: $(body.repository.clone_url)
  - name: GIT_REPO_NAME
    value: $(body.repository.name)
  - name: GIT_REPO_FULL_NAME
    value: $(body.repository.full_name)
