apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-app-config
  namespace: order-management
data:
  application.properties: |-
    quarkus.http.port=8083
    quarkus.swagger-ui.always-include=true
    quarkus.smallrye-openapi.path=/swagger
    quarkus.datasource.db-kind=postgresql
    quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-service.order-management.svc.cluster.local:5432/${POSTGRESQL_DATABASE}
    quarkus.hibernate-orm.database.generation=update
